[tool.poetry]
name = "applemusicdecrypt"
version = "0.1.0"
description = ""
authors = ["WorldObservationLog <wolc@duck.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.28.1"
regex = "^2025.7.34"
pydantic = "^2.7.0"
loguru = "^0.7.2"
six = "^1.16.0"
lxml = "^6.0.0"
beautifulsoup4 = "^4.13.5"
m3u8 = "^6.0.0"
tenacity = "^9.1.2"
prompt-toolkit = "^3.0.43"
winloop = { version = "^0.2.1", platform = "win32" }
uvloop = [{ version = "^0.21.0", platform = "linux" },
    { version = "^0.21.0", platform = "darwin" }]
prettytable = "^3.10.0"
pyventus = "^0.7.0"
grpcio = "^1.74.0"
grpcio-tools = "^1.74.0"
pywidevine = {git = "https://github.com/WorldObservationLog/pywidevine"}
creart = "^0.3.0"
mutagen = "^1.47.0"
hishel = "^0.1.3"
async-lru = "^2.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
