on:
  push:
    branches:
      - v2
  workflow_dispatch:

jobs:
  build_winodws:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
      - name: Create venv
        run: python -m venv .venv
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Prepare environment
        run: |
          cp config.example.toml config.toml
          echo .\.venv\Scripts\python.exe main.py > start.ps1
          echo .venv\Scripts\python.exe main.py > start.bat
      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppleMusicDecrypt-Windows
          path: AppleMusicDecrypt